version: "3.8"

services:
  ip_whitelist_builder:
    image: python:3.11-slim
    container_name: ip_whitelist_builder
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install requests && python build_list.py"
